### ISSUE TITLE
cut problem how to fix it?

### ISSUE THREAD

**Issue by camillychen** [JunweiLiang/aicity_action#1]
defaultdict(<class 'int'>, {'NA': 22, '3': 30, '14': 27, '2': 30, '8': 30, '5': 30, '11': 30, '17': 30, '7': 30, '15': 30, '9': 30, '0': 30, '4': 30, '1': 30, '10': 30, '16': 30, '6': 30, '12': 30, '13': 30})
user num: 5, action length min/max/median: 2, 120, 20.0
[16:15:39] D:\a\decord\decord\src\video\video_reader.cc:83: ERROR opening: ../data/A1_A2_videos/Rightside_window_user_id_24491_NoAudio_1.MP4, No such file or directory
Traceback (most recent call last):
  File "aicity_convert_anno.py", line 172, in <module>
    main(parser.parse_args())
  File "aicity_convert_anno.py", line 107, in main
    vcap = decord.VideoReader(video)
  File "C:\Users\asus\anaconda3\lib\site-packages\decord\video_reader.py", line 57, in __init__
    raise RuntimeError("Error reading " + uri + "...")
RuntimeError: Error reading ../data/A1_A2_videos/Rightside_window_user_id_24491_NoAudio_1.MP4...

**Comment by JunweiLiang** [comment]
The video files are not generated correctly from the last step. Check your ffmpeg outputs.

**Comment by camillychen** [comment]
Hello:

I want to check steps:

Step1. Put all video into the data/a1_a2_video
Step2.  Downloaded annotations to data/annotations

The data file with scripts file in the same path

Then, use below command:

$ python scripts/aicity_convert_anno.py
data/annotations/annotation_A1.edited.csv \
data/A1_A2_videos/ data/annotations/processed_anno_original.csv \
A1_cut.sh data/A1_clips/ --resolution=-2:540

==>that is cut video, is right?


Thank you


Junwei Liang ***@***.***>於 2022年5月14日 週六，下午8:11寫道：

**Comment by JunweiLiang** [comment]
Step 2 only generated `A1_cut.sh` for you to run the video cutting command using shell. I see that now, `aicity_convert_anno.py` fails since the videos are not placed correctly in ../data/A1_A2_videos/ . Check whether you have done step 1 correctly. List your files of ../data/A1_A2_videos/

**Comment by camillychen** [comment]
Hello:

could you tell me that file path is correct?
Put all video into the  C:\aicity_action-main\scripts\data\A1_A2_videos ==>include aicity_convert_anno.py

but,  that have other problem as below:
 C:\aicity_action-main\scripts\data\A1_A2_videos>python aicity_convert_anno.py data/annotations/annotation_A1.edited.csv    data/A1_A2_videos/ data/annotations/processed_anno_original.csv  A1_cut.sh data/A1_clips/ --resolution=-2:540
Traceback (most recent call last):
  File "aicity_convert_anno.py", line 172, in <module>
    main(parser.parse_args())
  File "aicity_convert_anno.py", line 72, in main
    for line in open(args.anno_file, "r").readlines()[1:]:
FileNotFoundError: [Errno 2] No such file or directory: 'data/annotations/annotation_A1.edited.csv'

thank you

**Comment by JunweiLiang** [comment]
No, it is not correct. The instructions are very clear where to run the scripts and where you can download `annotation_A1.edited.csv`.
![截屏2022-05-15 下午9 22 07](https://user-images.githubusercontent.com/22200250/168475045-e1c2a01f-a1cd-4bf4-9734-aaab8f0471f8.png)

**Comment by camillychen** [comment]
Hello :

Because i just only have 54.mp4   that run python cmd  cause some problem as below:
how to can fix it?
thank you


(base) C:\aicity_action-main>python scripts/aicity_convert_anno.py data/annotations/annotation_A1.edited.csv data/A1_A2_videos  data/annotations/processed_anno_original.csv A1_cut.sh data/A1_clips/ --resolution=-2:540
defaultdict(<class 'int'>, {'NA': 22, '3': 30, '14': 27, '2': 30, '8': 30, '5': 30, '11': 30, '17': 30, '7': 30, '15': 30, '9': 30, '0': 30, '4': 30, '1': 30, '10': 30, '16': 30, '6': 30, '12': 30, '13': 30})
user num: 5, action length min/max/median: 2, 120, 20.0
[19:54:08] D:\a\decord\decord\src\video\video_reader.cc:83: ERROR opening: data/A1_A2_videos\Right_window_user_id_24491_NoAudio_1.MP4, No such file or directory
Traceback (most recent call last):
  File "scripts/aicity_convert_anno.py", line 172, in <module>
    main(parser.parse_args())
  File "scripts/aicity_convert_anno.py", line 107, in main
    vcap = decord.VideoReader(video)
  File "C:\Users\asus\anaconda3\lib\site-packages\decord\video_reader.py", line 57, in __init__
    raise RuntimeError("Error reading " + uri + "...")
RuntimeError: Error reading data/A1_A2_videos\Right_window_user_id_24491_NoAudio_1.MP4...

**Comment by camillychen** [comment]
Hello:

If A1-A2_video only have 54.mp4 that run python aicity_convert_anno.py
==> error reading
data/A1_A2_videos\Right_window_iser_id24491_NoAudio_1.mp4…..

this problem how to can fix it?

Thank you

Junwei Liang ***@***.***>於 2022年5月15日 週日，下午9:24寫道：

**Comment by JunweiLiang** [comment]
I think it may have to do with the path splitter difference between Windows and Linux ("/" vs. "\"). Try using our code under Linux/Ubuntu.
