### ISSUE TITLE
缺少配置文件VITV2_FULL_B_16x4_CONV_448.yaml

### ISSUE THREAD

**Issue by Icanlighte** [JunweiLiang/aicity_action#3]
No such file or directory: '../../configs/VITV2_FULL_B_16x4_CONV_448.yaml'
作者您好，git仓里好像少了配置文件VITV2_FULL_B_16x4_CONV_448.yaml。。我尝试使用../../configs/Aicity/MVITV2_FULL_B_16x4_CONV_448.yaml去加载网络，但会出现torch.multiprocessing.spawn.ProcessExitedException: process 2 terminated with signal SIGBUS，推测是加载的模型结构和定义的结构不一致出现内存地址溢出的问题。看能否提供一下原配置文件呢

**Comment by JunweiLiang** [comment]
typo修复了；这个错误应该不是定义不同的原因，模型和yaml是对应的，不对应的话我在代码里有handle，会提示哪个tensor weight没有load。看看pytorch 版本是否是1.10-1.14，或者换一台机器试试
